OS:
  - 'xenial'
  - 'bionic'
  - 'focal'
  - 'rhel7'
  - 'rhel8'

RS_VERSIONS:
  '100.0.0':
    'build': '3026'
    'supported_os':
      - 'xenial'
      - 'bionic'
      - 'focal'
      - 'rhel7'
      - 'rhel8'
  '6.4.2':
    'build': '16'
    'supported_os':
      - 'xenial'
      - 'bionic'
      - 'focal'
      - 'rhel7'
      - 'rhel8'
  '6.4.0':
    'build': '48'
    'supported_os':
      - 'xenial'
      - 'bionic'
      - 'rhel7'
      - 'rhel8'
  '6.2.18':
    'build': '65'
    'supported_os':
      - 'xenial'
      - 'bionic'
      - 'rhel7'
      - 'rhel8'
  '6.2.12':
    'build': '82'
    'supported_os':
      - 'xenial'
      - 'bionic'
      - 'rhel7'
      - 'rhel8'
  '6.2.10':
    'build': '129'
    'supported_os':
      - 'xenial'
      - 'bionic'
      - 'rhel7'
      - 'rhel8'
  '6.2.8':
    'build': '53'
    'supported_os':
      - 'xenial'
      - 'bionic'
      - 'rhel7'
      - 'rhel8'
  '6.2.4':
    'build': '54'
    'supported_os':
      - 'xenial'
      - 'bionic'
      - 'rhel7'
  '6.0.20':
    'build': '101'
    'supported_os':
      - 'xenial'
      - 'bionic'
      - 'rhel7'
  '6.0.12':
    'build': '58'
    'supported_os':
      - 'xenial'
      - 'bionic'
      - 'rhel7'
  '6.0.8':
    'build': '32'
    'supported_os':
      - 'xenial'
      - 'bionic'
      - 'rhel7'
  '6.0.6':
    'build': '39'
    'supported_os':
      - 'xenial'
      - 'bionic'
      - 'rhel7'

OS_SUPPORTED_BY_MODULES:
  'json':
    'os_supported':
      - 'xenial'
      - 'bionic'
      - 'focal'
      - 'rhel7'
      - 'rhel8'

  'graph':
    'os_supported':
      - 'xenial'
      - 'bionic'
      - 'focal'
      - 'rhel7'
      - 'rhel8'

  'timeseries':
    'os_supported':
      - 'xenial'
      - 'bionic'
      - 'focal'
      - 'rhel7'
      - 'rhel8'

  'bloom':
    'os_supported':
      - 'xenial'
      - 'bionic'
      - 'focal'
      - 'rhel7'
      - 'rhel8'

  'gears':
    'os_supported':
      - 'xenial'
      - 'bionic'
      - 'rhel7'
      - 'rhel8'

  'search':
    'os_supported':
      - 'xenial'
      - 'bionic'
      - 'focal'
      - 'rhel7'
      - 'rhel8'

  'searchlight':
    'os_supported':
      - 'xenial'
      - 'bionic'
      - 'focal'
      - 'rhel7'
      - 'rhel8'

  'ai':
    'os_supported':
      - 'xenial'
      - 'bionic'
      - 'rhel7'
      - 'rhel8'

  'ailight':
    'os_supported':
      - 'xenial'
      - 'bionic'
      - 'rhel7'
      - 'rhel8'
